#district and site name check
unique(waste$site_name[waste$district_name == "Johannesburg MM"])
unique(waste$site_name[waste$district_name == "Ekurhuleni MM"])
unique(waste$site_name[waste$district_name == "Tshwane MM"])
unique(waste$site_name[waste$district_name == "Mangaung MM"])
unique(waste$site_name[waste$district_name == "Nelson Mandela Bay MM"])
unique(waste$site_name[waste$district_name == "Ethekwini MM"])
unique(waste$site_name[waste$district_name == "Umkhanyakude DM"])
unique(waste$site_name[waste$district_name == "Vhembe DM"])
unique(waste$site_name[waste$district_name == "Ehlanzeni DM"])
unique(waste$site_name[waste$district_name == "Ngaka Modiri Molema DM"])
unique(waste$site_name[waste$district_name == "Bojanala Platinum DM"])
unique(waste$site_name[waste$district_name == "Namakwa DM"])
unique(waste$site_name[waste$district_name == "Frances Baard DM"])
unique(waste$site_name[waste$district_name == "Cape Town MM"])
unique(waste$site_name[waste$district_name == "Nelson Mandela Bay MM"])
unique(waste$site_name[waste$district_name == "Buffalo City MM"])

#province and district name check
unique(waste$district_name[waste$site_province == "Gauteng"])
unique(waste$district_name[waste$site_province == "Free State"])
unique(waste$district_name[waste$site_province == "North West"])
unique(waste$district_name[waste$site_province == "Mpumalanga"])
unique(waste$district_name[waste$site_province == "Limpopo"])
unique(waste$district_name[waste$site_province == "Northern Cape"])
unique(waste$district_name[waste$site_province == "Western Cape"])
unique(waste$district_name[waste$site_province == "KwaZulu-Natal"])
unique(waste$district_name[waste$site_province == "Eastern Cape"])
